### ISSUE TITLE
Crash when checking for updates with poor/no network connections

### ISSUE THREAD

**Issue by jbellamycarter** [jbellamycarter/pepfoot#6]
The release update checker added to v1.2.0 causes pepFoot to crash when there is poor connectivity.

**Comment by vishalchem33-stack** [comment]
PepFoot crashed due to an error [2025-10-28 17:41:00.144616]:

Traceback (most recent call last):
  File "pepFootGui.py", line 933, in update_PepList
  File "pepFootGui.py", line 884, in digest
AttributeError: 'Main' object has no attribute 'data'

--End of Report--
